from django.urls import path
from .views import (
    VendorMeView,
    VendorAdminDetailView,
    VendorDashboardView,
    VendorProductListView,
    VendorProductDetailView,
    VendorOrderListView,
    VendorCustomerListView,
    VendorAnalyticsView,
    VendorPublicListView,
    VendorPublicByCategoryView,
    VendorCustomOrderListView,
    VendorMediaUploadView,
    VendorShippingListView,
    VendorShippingDetailView,
    VendorCatalogFilterConfigView,
)

urlpatterns = [
    path("public/", VendorPublicListView.as_view(), name="vendor-public-list"),
    path("public/by-category/<slug:category_slug>/", VendorPublicByCategoryView.as_view(), name="vendor-public-by-category"),
    path("me/", VendorMeView.as_view(), name="vendor-me"),
    path("<slug:slug>/", VendorAdminDetailView.as_view(), name="vendor-admin-detail"),
    path("me/dashboard/", VendorDashboardView.as_view(), name="vendor-dashboard"),
    path("me/products/", VendorProductListView.as_view(), name="vendor-products"),
    path("me/products/<int:pk>/", VendorProductDetailView.as_view(), name="vendor-product-detail"),
    path("me/orders/", VendorOrderListView.as_view(), name="vendor-orders"),
    path("me/customers/", VendorCustomerListView.as_view(), name="vendor-customers"),
    path("me/analytics/", VendorAnalyticsView.as_view(), name="vendor-analytics"),
    path("me/upload/", VendorMediaUploadView.as_view(), name="vendor-media-upload"),
    path("me/custom-orders/", VendorCustomOrderListView.as_view(), name="vendor-custom-orders"),
    path("me/custom-orders/<uuid:pk>/", VendorCustomOrderListView.as_view(), name="vendor-custom-order-detail"),
    path("me/shipping/", VendorShippingListView.as_view(), name="vendor-shipping"),
    path("me/shipping/<int:pk>/", VendorShippingDetailView.as_view(), name="vendor-shipping-detail"),
    path("me/catalog-filter-config/", VendorCatalogFilterConfigView.as_view(), name="vendor-catalog-filter-config"),
]
