from django.urls import path
from .views import (
    AdminLoginView,
    AdminDashboardView,
    AdminAnalyticsView,
    AdminOrderListView,
    AdminOrderUpdateView,
    AdminProductListView,
    AdminProductDetailView,
    AdminProductStockView,
    AdminCategoryListView,
    AdminCategoryDetailView,
    AdminArtistListView,
    AdminArtistDetailView,
    AdminUserListView,
    AdminUserToggleView,
    AdminPromoListView,
    AdminPromoDetailView,
    AdminReviewListView,
    AdminReviewApproveView,
    AdminAuctionListView,
    AdminAuctionDetailView,
    AdminHeroListView,
    AdminHeroDetailView,
    AdminBannerListView,
    AdminBannerDetailView,
    AdminNewsletterListView,
    AdminConversationListView,
    AdminSettingsView,
    AdminBadgeListView,
    AdminXPRuleListView,
    AdminAuditLogView,
)

urlpatterns = [
    path("auth/login/", AdminLoginView.as_view(), name="admin-login"),
    path("dashboard/", AdminDashboardView.as_view(), name="admin-dashboard"),
    path("analytics/", AdminAnalyticsView.as_view(), name="admin-analytics"),
    path("orders/", AdminOrderListView.as_view(), name="admin-orders"),
    path("orders/<uuid:pk>/", AdminOrderUpdateView.as_view(), name="admin-order-update"),
    path("products/", AdminProductListView.as_view(), name="admin-products"),
    path("products/<int:pk>/", AdminProductDetailView.as_view(), name="admin-product-detail"),
    path("products/variants/<int:pk>/stock/", AdminProductStockView.as_view(), name="admin-product-stock"),
    path("categories/", AdminCategoryListView.as_view(), name="admin-categories"),
    path("categories/<int:pk>/", AdminCategoryDetailView.as_view(), name="admin-category-detail"),
    path("artists/", AdminArtistListView.as_view(), name="admin-artists"),
    path("artists/<int:pk>/", AdminArtistDetailView.as_view(), name="admin-artist-detail"),
    path("users/", AdminUserListView.as_view(), name="admin-users"),
    path("users/<uuid:pk>/toggle/", AdminUserToggleView.as_view(), name="admin-user-toggle"),
    path("promos/", AdminPromoListView.as_view(), name="admin-promos"),
    path("promos/<int:pk>/", AdminPromoDetailView.as_view(), name="admin-promo-detail"),
    path("reviews/", AdminReviewListView.as_view(), name="admin-reviews"),
    path("reviews/<int:pk>/approve/", AdminReviewApproveView.as_view(), name="admin-review-approve"),
    path("auctions/", AdminAuctionListView.as_view(), name="admin-auctions"),
    path("auctions/<int:pk>/", AdminAuctionDetailView.as_view(), name="admin-auction-detail"),
    path("hero/", AdminHeroListView.as_view(), name="admin-hero"),
    path("hero/<int:pk>/", AdminHeroDetailView.as_view(), name="admin-hero-detail"),
    path("banners/", AdminBannerListView.as_view(), name="admin-banners"),
    path("banners/<int:pk>/", AdminBannerDetailView.as_view(), name="admin-banner-detail"),
    path("newsletter/", AdminNewsletterListView.as_view(), name="admin-newsletter"),
    path("inbox/", AdminConversationListView.as_view(), name="admin-inbox"),
    path("settings/", AdminSettingsView.as_view(), name="admin-settings"),
    path("gamification/badges/", AdminBadgeListView.as_view(), name="admin-badges"),
    path("gamification/xp-rules/", AdminXPRuleListView.as_view(), name="admin-xp-rules"),
    path("audit-log/", AdminAuditLogView.as_view(), name="admin-audit-log"),
]
