from django.urls import path
from .views import (
    AdminLoginView,
    AdminDashboardView,
    AdminAnalyticsView,
    AdminSuperAnalyticsView,
    AdminOrderListView,
    AdminOrderUpdateView,
    AdminProductListView,
    AdminProductDetailView,
    AdminProductStockView,
    AdminCategoryListView,
    AdminCategoryDetailView,
    AdminArtistListView,
    AdminArtistDetailView,
    AdminUserListView,
    AdminUserPointAdjustmentView,
    AdminUserToggleView,
    AdminPromoListView,
    AdminPromoDetailView,
    AdminCreatorApplicationListView,
    AdminCreatorApplicationDetailView,
    AdminContentCreatorListView,
    AdminContentCreatorDetailView,
    AdminCreatorAcceptedWithoutVoucherView,
    AdminCreatorLedgerListView,
    AdminCreatorVoucherUsesView,
    AdminCreatorPayoutListView,
    AdminCreatorPayoutDetailView,
    AdminCreatorPayoutMinimumView,
    AdminReviewListView,
    AdminReviewApproveView,
    AdminHomepageReviewListView,
    AdminHomepageReviewDetailView,
    AdminCommunitySocialLinkListView,
    AdminCommunitySocialLinkDetailView,
    AdminTrustBarItemListView,
    AdminTrustBarItemDetailView,
    AdminFandomBrandListView,
    AdminFandomBrandDetailView,
    AdminFAQListView,
    AdminFAQDetailView,
    AdminAuctionListView,
    AdminAuctionDetailView,
    AdminHeroListView,
    AdminHeroDetailView,
    AdminBannerListView,
    AdminBannerDetailView,
    AdminAnnouncementBarView,
    AdminNewsletterListView,
    AdminConversationListView,
    AdminSettingsView,
    AdminPointsMarketItemListView,
    AdminPointsMarketItemDetailView,
    AdminPointTransactionListView,
    AdminPointsMarketRedemptionListView,
    AdminPointsMarketRedemptionDetailView,
    AdminAuditLogView,
    AdminBlogPostListView,
    AdminBlogPostDetailView,
    AdminDeliveryOptionListView,
    AdminDeliveryOptionDetailView,
    AdminProcessingOptionListView,
    AdminProcessingOptionDetailView,
    AdminProductMediaView,
    AdminProductMediaReorderView,
    AdminMediaUploadView,
    AdminSizeVariantView,
    AdminProductExportView,
    AdminProductImportView,
    AdminVendorOpsView,
    AdminVendorBulkSaleView,
    AdminPageSectionListView,
    AdminPageSectionDetailView,
    AdminCatalogFilterConfigView,
    AdminEmailTemplateListView,
    AdminEmailTemplateDetailView,
    AdminEmailTemplateSeedView,
    AdminEmailLogListView,
    AdminAuctionSubscriberListView,
    AdminContactMessageListView,
    AdminContactMessageDetailView,
)

urlpatterns = [
    path("auth/login/", AdminLoginView.as_view(), name="admin-login"),
    path("dashboard/", AdminDashboardView.as_view(), name="admin-dashboard"),
    path("analytics/", AdminAnalyticsView.as_view(), name="admin-analytics"),
    path("analytics/super/", AdminSuperAnalyticsView.as_view(), name="admin-super-analytics"),
    path("orders/", AdminOrderListView.as_view(), name="admin-orders"),
    path("orders/<uuid:pk>/", AdminOrderUpdateView.as_view(), name="admin-order-update"),
    path("products/", AdminProductListView.as_view(), name="admin-products"),
    path("products/<int:pk>/", AdminProductDetailView.as_view(), name="admin-product-detail"),
    path("products/variants/<int:pk>/stock/", AdminProductStockView.as_view(), name="admin-product-stock"),
    path("media/upload/", AdminMediaUploadView.as_view(), name="admin-media-upload"),
    path("products/media/", AdminProductMediaView.as_view(), name="admin-product-media"),
    path("products/media/<int:image_id>/", AdminProductMediaView.as_view(), name="admin-product-media-detail"),
    path("products/media/reorder/", AdminProductMediaReorderView.as_view(), name="admin-product-media-reorder"),
    path("categories/", AdminCategoryListView.as_view(), name="admin-categories"),
    path("categories/<int:pk>/", AdminCategoryDetailView.as_view(), name="admin-category-detail"),
    path("artists/", AdminArtistListView.as_view(), name="admin-artists"),
    path("artists/<int:pk>/", AdminArtistDetailView.as_view(), name="admin-artist-detail"),
    path("users/", AdminUserListView.as_view(), name="admin-users"),
    path("users/<uuid:pk>/toggle/", AdminUserToggleView.as_view(), name="admin-user-toggle"),
    path("users/<uuid:pk>/points-adjustment/", AdminUserPointAdjustmentView.as_view(), name="admin-user-points-adjustment"),
    path("promos/", AdminPromoListView.as_view(), name="admin-promos"),
    path("promos/<int:pk>/", AdminPromoDetailView.as_view(), name="admin-promo-detail"),
    path("creators/applications/", AdminCreatorApplicationListView.as_view(), name="admin-creator-applications"),
    path("creators/applications/<int:pk>/", AdminCreatorApplicationDetailView.as_view(), name="admin-creator-application-detail"),
    path("creators/accepted-without-voucher/", AdminCreatorAcceptedWithoutVoucherView.as_view(), name="admin-creator-accepted-no-voucher"),
    path("creators/", AdminContentCreatorListView.as_view(), name="admin-creators"),
    path("creators/<int:pk>/", AdminContentCreatorDetailView.as_view(), name="admin-creator-detail"),
    path("creators/ledger/", AdminCreatorLedgerListView.as_view(), name="admin-creator-ledger"),
    path("creators/voucher-uses/", AdminCreatorVoucherUsesView.as_view(), name="admin-creator-voucher-uses"),
    path("creators/payouts/", AdminCreatorPayoutListView.as_view(), name="admin-creator-payouts"),
    path("creators/payouts/<int:pk>/", AdminCreatorPayoutDetailView.as_view(), name="admin-creator-payout-detail"),
    path("creators/payout-minimum/", AdminCreatorPayoutMinimumView.as_view(), name="admin-creator-payout-minimum"),
    path("reviews/", AdminHomepageReviewListView.as_view(), name="admin-homepage-reviews"),
    path("reviews/<int:pk>/", AdminHomepageReviewDetailView.as_view(), name="admin-homepage-review-detail"),
    path("community-links/", AdminCommunitySocialLinkListView.as_view(), name="admin-community-links"),
    path("community-links/<int:pk>/", AdminCommunitySocialLinkDetailView.as_view(), name="admin-community-link-detail"),
    path("trust-bar/", AdminTrustBarItemListView.as_view(), name="admin-trust-bar"),
    path("trust-bar/<int:pk>/", AdminTrustBarItemDetailView.as_view(), name="admin-trust-bar-detail"),
    path("fandoms/", AdminFandomBrandListView.as_view(), name="admin-fandoms"),
    path("fandoms/<int:pk>/", AdminFandomBrandDetailView.as_view(), name="admin-fandom-detail"),
    path("faqs/", AdminFAQListView.as_view(), name="admin-faqs"),
    path("faqs/<int:pk>/", AdminFAQDetailView.as_view(), name="admin-faq-detail"),
    path("product-reviews/", AdminReviewListView.as_view(), name="admin-product-reviews"),
    path("product-reviews/<int:pk>/approve/", AdminReviewApproveView.as_view(), name="admin-product-review-approve"),
    path("auctions/", AdminAuctionListView.as_view(), name="admin-auctions"),
    path("auctions/<int:pk>/", AdminAuctionDetailView.as_view(), name="admin-auction-detail"),
    path("hero/", AdminHeroListView.as_view(), name="admin-hero"),
    path("hero/<int:pk>/", AdminHeroDetailView.as_view(), name="admin-hero-detail"),
    path("banners/", AdminBannerListView.as_view(), name="admin-banners"),
    path("banners/<int:pk>/", AdminBannerDetailView.as_view(), name="admin-banner-detail"),
    path("announcement/", AdminAnnouncementBarView.as_view(), name="admin-announcement"),
    path("newsletter/", AdminNewsletterListView.as_view(), name="admin-newsletter"),
    path("inbox/", AdminConversationListView.as_view(), name="admin-inbox"),
    path("settings/", AdminSettingsView.as_view(), name="admin-settings"),
    path("gamification/market/", AdminPointsMarketItemListView.as_view(), name="admin-points-market"),
    path("gamification/market/<int:pk>/", AdminPointsMarketItemDetailView.as_view(), name="admin-points-market-detail"),
    path("gamification/transactions/", AdminPointTransactionListView.as_view(), name="admin-point-transactions"),
    path("gamification/redemptions/", AdminPointsMarketRedemptionListView.as_view(), name="admin-points-redemptions"),
    path("gamification/redemptions/<int:pk>/", AdminPointsMarketRedemptionDetailView.as_view(), name="admin-points-redemption-detail"),
    path("blog/", AdminBlogPostListView.as_view(), name="admin-blog"),
    path("blog/<int:pk>/", AdminBlogPostDetailView.as_view(), name="admin-blog-detail"),
    path("audit-log/", AdminAuditLogView.as_view(), name="admin-audit-log"),
    path("delivery-options/", AdminDeliveryOptionListView.as_view(), name="admin-delivery-options"),
    path("delivery-options/<int:pk>/", AdminDeliveryOptionDetailView.as_view(), name="admin-delivery-option-detail"),
    path("processing-options/", AdminProcessingOptionListView.as_view(), name="admin-processing-options"),
    path("processing-options/<int:pk>/", AdminProcessingOptionDetailView.as_view(), name="admin-processing-option-detail"),
    path("vendors/<slug:slug>/ops/", AdminVendorOpsView.as_view(), name="admin-vendor-ops"),
    path("vendors/<slug:slug>/sale/", AdminVendorBulkSaleView.as_view(), name="admin-vendor-bulk-sale"),
    path("page-sections/", AdminPageSectionListView.as_view(), name="admin-page-sections"),
    path("page-sections/<int:pk>/", AdminPageSectionDetailView.as_view(), name="admin-page-section-detail"),
    path("catalog-filter-config/", AdminCatalogFilterConfigView.as_view(), name="admin-catalog-filter-config"),
    path("size-variants/", AdminSizeVariantView.as_view(), name="admin-size-variants"),
    path("size-variants/<int:sv_id>/", AdminSizeVariantView.as_view(), name="admin-size-variant-detail"),
    path("products/export/", AdminProductExportView.as_view(), name="admin-product-export"),
    path("products/import/", AdminProductImportView.as_view(), name="admin-product-import"),
    path("email-templates/", AdminEmailTemplateListView.as_view(), name="admin-email-templates"),
    path("email-templates/seed/", AdminEmailTemplateSeedView.as_view(), name="admin-email-templates-seed"),
    path("email-templates/<int:pk>/", AdminEmailTemplateDetailView.as_view(), name="admin-email-template-detail"),
    path("email-logs/", AdminEmailLogListView.as_view(), name="admin-email-logs"),
    path("auction-subscribers/", AdminAuctionSubscriberListView.as_view(), name="admin-auction-subscribers"),
    path("contact-messages/", AdminContactMessageListView.as_view(), name="admin-contact-messages"),
    path("contact-messages/<int:pk>/", AdminContactMessageDetailView.as_view(), name="admin-contact-message-detail"),
]
