from django.urls import path
from .views import (
    AdminLoginView,
    AdminDashboardView,
    AdminAnalyticsView,
    AdminSuperAnalyticsView,
    AdminOrderListView,
    AdminOrderUpdateView,
    AdminProductListView,
    AdminProductDetailView,
    AdminProductStockView,
    AdminCategoryListView,
    AdminCategoryDetailView,
    AdminArtistListView,
    AdminArtistDetailView,
    AdminUserListView,
    AdminUserToggleView,
    AdminPromoListView,
    AdminPromoDetailView,
    AdminReviewListView,
    AdminReviewApproveView,
    AdminHomepageReviewListView,
    AdminHomepageReviewDetailView,
    AdminCommunitySocialLinkListView,
    AdminCommunitySocialLinkDetailView,
    AdminFAQListView,
    AdminFAQDetailView,
    AdminAuctionListView,
    AdminAuctionDetailView,
    AdminHeroListView,
    AdminHeroDetailView,
    AdminBannerListView,
    AdminBannerDetailView,
    AdminAnnouncementBarView,
    AdminNewsletterListView,
    AdminConversationListView,
    AdminSettingsView,
    AdminBadgeListView,
    AdminBadgeDetailView,
    AdminXPRuleListView,
    AdminXPRuleDetailView,
    AdminAuditLogView,
    AdminBlogPostListView,
    AdminBlogPostDetailView,
    AdminDeliveryOptionListView,
    AdminDeliveryOptionDetailView,
    AdminProcessingOptionListView,
    AdminProcessingOptionDetailView,
    AdminProductMediaView,
    AdminProductMediaReorderView,
    AdminMediaUploadView,
    AdminSizeVariantView,
    AdminProductExportView,
    AdminProductImportView,
    AdminVendorOpsView,
    AdminVendorBulkSaleView,
    AdminPageSectionListView,
    AdminPageSectionDetailView,
    AdminCatalogFilterConfigView,
)

urlpatterns = [
    path("auth/login/", AdminLoginView.as_view(), name="admin-login"),
    path("dashboard/", AdminDashboardView.as_view(), name="admin-dashboard"),
    path("analytics/", AdminAnalyticsView.as_view(), name="admin-analytics"),
    path("analytics/super/", AdminSuperAnalyticsView.as_view(), name="admin-super-analytics"),
    path("orders/", AdminOrderListView.as_view(), name="admin-orders"),
    path("orders/<uuid:pk>/", AdminOrderUpdateView.as_view(), name="admin-order-update"),
    path("products/", AdminProductListView.as_view(), name="admin-products"),
    path("products/<int:pk>/", AdminProductDetailView.as_view(), name="admin-product-detail"),
    path("products/variants/<int:pk>/stock/", AdminProductStockView.as_view(), name="admin-product-stock"),
    path("media/upload/", AdminMediaUploadView.as_view(), name="admin-media-upload"),
    path("products/media/", AdminProductMediaView.as_view(), name="admin-product-media"),
    path("products/media/<int:image_id>/", AdminProductMediaView.as_view(), name="admin-product-media-detail"),
    path("products/media/reorder/", AdminProductMediaReorderView.as_view(), name="admin-product-media-reorder"),
    path("categories/", AdminCategoryListView.as_view(), name="admin-categories"),
    path("categories/<int:pk>/", AdminCategoryDetailView.as_view(), name="admin-category-detail"),
    path("artists/", AdminArtistListView.as_view(), name="admin-artists"),
    path("artists/<int:pk>/", AdminArtistDetailView.as_view(), name="admin-artist-detail"),
    path("users/", AdminUserListView.as_view(), name="admin-users"),
    path("users/<uuid:pk>/toggle/", AdminUserToggleView.as_view(), name="admin-user-toggle"),
    path("promos/", AdminPromoListView.as_view(), name="admin-promos"),
    path("promos/<int:pk>/", AdminPromoDetailView.as_view(), name="admin-promo-detail"),
    path("reviews/", AdminHomepageReviewListView.as_view(), name="admin-homepage-reviews"),
    path("reviews/<int:pk>/", AdminHomepageReviewDetailView.as_view(), name="admin-homepage-review-detail"),
    path("community-links/", AdminCommunitySocialLinkListView.as_view(), name="admin-community-links"),
    path("community-links/<int:pk>/", AdminCommunitySocialLinkDetailView.as_view(), name="admin-community-link-detail"),
    path("faqs/", AdminFAQListView.as_view(), name="admin-faqs"),
    path("faqs/<int:pk>/", AdminFAQDetailView.as_view(), name="admin-faq-detail"),
    path("product-reviews/", AdminReviewListView.as_view(), name="admin-product-reviews"),
    path("product-reviews/<int:pk>/approve/", AdminReviewApproveView.as_view(), name="admin-product-review-approve"),
    path("auctions/", AdminAuctionListView.as_view(), name="admin-auctions"),
    path("auctions/<int:pk>/", AdminAuctionDetailView.as_view(), name="admin-auction-detail"),
    path("hero/", AdminHeroListView.as_view(), name="admin-hero"),
    path("hero/<int:pk>/", AdminHeroDetailView.as_view(), name="admin-hero-detail"),
    path("banners/", AdminBannerListView.as_view(), name="admin-banners"),
    path("banners/<int:pk>/", AdminBannerDetailView.as_view(), name="admin-banner-detail"),
    path("announcement/", AdminAnnouncementBarView.as_view(), name="admin-announcement"),
    path("newsletter/", AdminNewsletterListView.as_view(), name="admin-newsletter"),
    path("inbox/", AdminConversationListView.as_view(), name="admin-inbox"),
    path("settings/", AdminSettingsView.as_view(), name="admin-settings"),
    path("gamification/badges/", AdminBadgeListView.as_view(), name="admin-badges"),
    path("gamification/badges/<int:pk>/", AdminBadgeDetailView.as_view(), name="admin-badge-detail"),
    path("gamification/xp-rules/", AdminXPRuleListView.as_view(), name="admin-xp-rules"),
    path("gamification/xp-rules/<int:pk>/", AdminXPRuleDetailView.as_view(), name="admin-xp-rule-detail"),
    path("blog/", AdminBlogPostListView.as_view(), name="admin-blog"),
    path("blog/<int:pk>/", AdminBlogPostDetailView.as_view(), name="admin-blog-detail"),
    path("audit-log/", AdminAuditLogView.as_view(), name="admin-audit-log"),
    path("delivery-options/", AdminDeliveryOptionListView.as_view(), name="admin-delivery-options"),
    path("delivery-options/<int:pk>/", AdminDeliveryOptionDetailView.as_view(), name="admin-delivery-option-detail"),
    path("processing-options/", AdminProcessingOptionListView.as_view(), name="admin-processing-options"),
    path("processing-options/<int:pk>/", AdminProcessingOptionDetailView.as_view(), name="admin-processing-option-detail"),
    path("vendors/<slug:slug>/ops/", AdminVendorOpsView.as_view(), name="admin-vendor-ops"),
    path("vendors/<slug:slug>/sale/", AdminVendorBulkSaleView.as_view(), name="admin-vendor-bulk-sale"),
    path("page-sections/", AdminPageSectionListView.as_view(), name="admin-page-sections"),
    path("page-sections/<int:pk>/", AdminPageSectionDetailView.as_view(), name="admin-page-section-detail"),
    path("catalog-filter-config/", AdminCatalogFilterConfigView.as_view(), name="admin-catalog-filter-config"),
    path("size-variants/", AdminSizeVariantView.as_view(), name="admin-size-variants"),
    path("size-variants/<int:sv_id>/", AdminSizeVariantView.as_view(), name="admin-size-variant-detail"),
    path("products/export/", AdminProductExportView.as_view(), name="admin-product-export"),
    path("products/import/", AdminProductImportView.as_view(), name="admin-product-import"),
]
