# Generated by Django 5.1.4 on 2026-07-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0001_creator_vouchers'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentcreator',
            name='country',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='creatorapplication',
            name='country',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='creatorledgerentry',
            name='fx_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creatorledgerentry',
            name='fx_rate',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='creatorledgerentry',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='creatorledgerentry',
            name='original_currency',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.CreateModel(
            name='FxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('from_currency', models.CharField(max_length=10)),
                ('to_currency', models.CharField(max_length=10)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=14)),
                ('source', models.CharField(default='NBG', max_length=50)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'creator_fx_rates',
                'ordering': ['-date'],
                'unique_together': {('date', 'from_currency', 'to_currency')},
            },
        ),
    ]
