# Generated by Django 5.1.4 on 2026-07-24 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0003_badge_prizes_and_grants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Content creator who earns commission when this code is used.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_promo_codes', to=settings.AUTH_USER_MODEL),
        ),
    ]
