# Generated by Django 5.1.4 on 2026-08-17 09:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0005_promocode_products_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userpromogrant',
            name='source',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterUniqueTogether(
            name='userpromogrant',
            unique_together={('user', 'promo', 'source')},
        ),
        migrations.RemoveField(
            model_name='userpromogrant',
            name='source_badge',
        ),
    ]
