# Generated by Django 5.1.4 on 2026-07-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content_blocks',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
