# Generated by Django 5.1.4 on 2026-07-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_add_english_translation_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content_ka',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title_ka',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
