# Generated by Django 5.1.4 on 2026-08-08 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogpost_content_en_alter_blogpost_content_ka_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='content_ru',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='excerpt_ru',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='title_ru',
        ),
    ]
