# Generated by Django 5.1.4 on 2026-07-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='contact_attachments/'),
        ),
    ]
