# Generated by Django 5.1.4 on 2026-06-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist_name', models.CharField(blank=True, max_length=255)),
                ('image_url', models.URLField(blank=True)),
                ('starting_bid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ends_at', models.DateTimeField()),
                ('is_live', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'auctions',
                'ordering': ['ends_at'],
            },
        ),
        migrations.CreateModel(
            name='AuctionBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'auction_bids',
                'ordering': ['-placed_at'],
            },
        ),
    ]
