# Generated by Django 5.1.4 on 2026-06-30 08:11

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    Auction = apps.get_model("auctions", "Auction")
    seen = set()
    for auction in Auction.objects.all().order_by("id"):
        base = slugify(auction.title) or f"auction-{auction.id}"
        candidate = base
        n = 1
        while candidate in seen or Auction.objects.filter(slug=candidate).exclude(pk=auction.pk).exists():
            candidate = f"{base}-{n}"
            n += 1
        seen.add(candidate)
        auction.slug = candidate
        auction.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='slug',
            field=models.SlugField(blank=True, max_length=280, null=True),
        ),
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='auction',
            name='slug',
            field=models.SlugField(blank=True, max_length=280, unique=True),
        ),
    ]
