# Generated by Django 5.1.4 on 2026-07-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auctionsubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='meta_description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='auction',
            name='meta_description_en',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='meta_description_ka',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='meta_description_ru',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='auction',
            name='meta_keywords_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='meta_keywords_ka',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='meta_keywords_ru',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='auction',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='meta_title_ka',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='meta_title_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='title_ka',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
