# Generated by Django 5.1.4 on 2026-08-08 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auction_meta_description_auction_meta_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='meta_description_ru',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='meta_keywords_ru',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='meta_title_ru',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='title_ru',
        ),
    ]
