# Generated by Django 5.1.4 on 2026-08-10 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_auction_meta_description_ru_and_more'),
        ('products', '0025_remove_artist_bio_ru_remove_artist_name_ru_and_more'),
        ('vendors', '0008_remove_vendor_description_ru_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='inventory_reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auction',
            name='inventory_was_last_ready_unit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auction',
            name='is_replacement_winner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auction',
            name='reserved_size_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_for_auctions', to='products.sizevariant'),
        ),
        migrations.AddField(
            model_name='auctionbid',
            name='disqualification_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='auctionbid',
            name='disqualified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auctionbid',
            name='is_disqualified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AuctionBidderBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_auction_bans', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_bans', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auction_bans', to='vendors.vendor')),
            ],
            options={
                'db_table': 'auction_bidder_bans',
                'constraints': [models.UniqueConstraint(fields=('user', 'vendor'), name='unique_auction_bidder_ban_scope')],
            },
        ),
    ]
