# Generated by Django 5.1.4 on 2026-08-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auction_inventory_reserved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='shipping_price_gel',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='auction',
            name='shipping_price_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='auctionbid',
            name='fx_rate_used',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='auctionbid',
            name='submitted_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='auctionbid',
            name='submitted_currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
