# Generated by Django 5.1.4 on 2026-08-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_google_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lifetime_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='spendable_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
