# Generated by Django 5.1.4 on 2026-08-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_lifetime_points_user_spendable_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lifetime_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='spendable_points',
            field=models.IntegerField(default=0),
        ),
    ]
