# Generated by Django 5.1.4 on 2026-06-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='custom_cover_url',
            field=models.URLField(blank=True, help_text='Preview / hero image shown on the custom order selection card'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='custom_product_description',
            field=models.TextField(blank=True, help_text='Short blurb shown on the custom order page'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='custom_product_type',
            field=models.CharField(blank=True, help_text="e.g. '3D Panel Poster' or '3D Figure'", max_length=100),
        ),
    ]
