# Generated by Django 5.1.4 on 2026-07-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_vendor_merchant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='gift_wrap_price_gel',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='vendor',
            name='gift_wrap_price_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='vendor',
            name='shipping_email_body',
            field=models.TextField(blank=True, default='Hi {{customer_name}},\n\nGreat news — your order {{order_number}} has shipped!{{tracking_info}}\n\nThank you for shopping with us!'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='shipping_email_subject',
            field=models.CharField(blank=True, default='Your order {{order_number}} has shipped!', max_length=255),
        ),
    ]
