# Generated by Django 5.1.4 on 2026-07-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_vendor_ops_and_page_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='description_ka',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='meta_description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='vendor',
            name='meta_description_en',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='meta_description_ka',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='meta_description_ru',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='vendor',
            name='meta_keywords_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='meta_keywords_ka',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='meta_keywords_ru',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vendor',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='meta_title_ka',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='meta_title_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='name_ka',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
