# Generated by Django 5.1.4 on 2026-08-08 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_vendor_description_en_vendor_description_ka_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='meta_description_ru',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='meta_keywords_ru',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='meta_title_ru',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='name_ru',
        ),
    ]
