# Generated by Django 5.1.4 on 2026-07-11 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_sender_kind(apps, schema_editor):
    Message = apps.get_model("messaging", "Message")
    for msg in Message.objects.filter(from_role="admin"):
        msg.sender_kind = "superadmin"
        msg.save(update_fields=["sender_kind"])


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_message_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender_kind',
            field=models.CharField(choices=[('customer', 'Customer'), ('superadmin', 'Superadmin'), ('vendor', 'Vendor')], default='customer', max_length=12),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_sender_kind, migrations.RunPython.noop),
    ]
