# Generated by Django 5.1.4 on 2026-08-11 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auctionchatmessage_deleted_at_and_more'),
        ('messaging', '0006_message_sender_kind'),
        ('vendors', '0009_normalize_default_vendor_identities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_inbox_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='deletion_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ChatReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('auction', 'Auction message'), ('inbox', 'Inbox message')], max_length=12)),
                ('target_id', models.PositiveBigIntegerField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=12)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_reports', to='auctions.auction')),
                ('reported_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_chat_messages', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_chat_reports', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_reports', to='vendors.vendor')),
            ],
            options={
                'db_table': 'chat_reports',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('reporter', 'target_type', 'target_id'), name='unique_chat_report_per_user')],
            },
        ),
        migrations.CreateModel(
            name='ChatRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('all', 'All chat'), ('auction', 'Auction chat'), ('inbox', 'Inbox')], default='all', max_length=12)),
                ('is_banned', models.BooleanField(default=False)),
                ('muted_until', models.DateTimeField(blank=True, null=True)),
                ('requires_admin_review', models.BooleanField(default=False)),
                ('strike_count', models.PositiveSmallIntegerField(default=0)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_restrictions', to='auctions.auction')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_chat_restrictions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_restrictions', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_restrictions', to='vendors.vendor')),
            ],
            options={
                'db_table': 'chat_restrictions',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'channel'], name='chat_restri_user_id_453879_idx'), models.Index(fields=['vendor', 'channel'], name='chat_restri_vendor__bf4638_idx'), models.Index(fields=['auction', 'channel'], name='chat_restri_auction_959234_idx')],
            },
        ),
        migrations.CreateModel(
            name='RiskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=40)),
                ('outcome', models.CharField(choices=[('allowed', 'Allowed'), ('rejected', 'Rejected'), ('admin', 'Admin action')], max_length=12)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('ip_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('user_agent_hash', models.CharField(blank=True, max_length=64)),
                ('device_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('auction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_events', to='auctions.auction')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_events', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_events', to='vendors.vendor')),
            ],
            options={
                'db_table': 'risk_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vendor', 'event_type', 'created_at'], name='risk_events_vendor__b0d775_idx')],
            },
        ),
    ]
