# Generated by Django 5.1.4 on 2026-07-16 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0006_vendor_ops_and_page_sections'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(choices=[('order_confirmed', 'Order Confirmed'), ('order_shipped', 'Order Shipped'), ('custom_order_shipped', 'Custom Order Shipped'), ('auction_new', 'New Auction Notification'), ('auction_won', 'Auction Won'), ('password_reset', 'Password Reset'), ('welcome', 'Welcome / Registration'), ('custom', 'Custom / One-off')], max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=300)),
                ('html_body', models.TextField(blank=True, help_text='Full HTML from the editor')),
                ('design_json', models.JSONField(blank=True, default=dict, help_text='GrapesJS project JSON for re-editing')),
                ('variables', models.JSONField(blank=True, default=list, help_text='Available placeholders, e.g. ["product_name","tracking_number"]')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(blank=True, help_text='NULL = platform-wide template', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='vendors.vendor')),
            ],
            options={
                'db_table': 'email_templates',
                'ordering': ['-updated_at'],
                'unique_together': {('vendor', 'event_key')},
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=300)),
                ('event_key', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], default='sent', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='emails.emailtemplate')),
            ],
            options={
                'db_table': 'email_logs',
                'ordering': ['-sent_at'],
            },
        ),
    ]
