# Generated by Django 5.1.4 on 2026-07-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='event_key',
            field=models.CharField(choices=[('order_confirmed', 'Order Confirmed'), ('order_shipped', 'Order Shipped'), ('review_request', 'Review Request'), ('review_request', 'Review Request'), ('custom_order_shipped', 'Custom Order Shipped'), ('auction_new', 'New Auction Notification'), ('auction_won', 'Auction Won'), ('password_reset', 'Password Reset'), ('welcome', 'Welcome / Registration'), ('custom', 'Custom / One-off')], max_length=50),
        ),
    ]
