# Generated by Django 5.1.4 on 2026-08-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_alter_emailtemplate_event_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='event_key',
            field=models.CharField(choices=[('order_confirmed', 'Order Confirmed'), ('order_shipped', 'Order Shipped'), ('review_request', 'Review Request'), ('custom_order_shipped', 'Custom Order Shipped'), ('auction_new', 'New Auction Notification'), ('auction_won', 'Auction Won'), ('auction_second_chance', 'Auction Replacement Winner'), ('password_reset', 'Password Reset'), ('welcome', 'Welcome / Registration'), ('newsletter_welcome', 'Newsletter Welcome'), ('custom', 'Custom / One-off')], max_length=50),
        ),
    ]
