# Generated by Django 5.1.4 on 2026-07-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslide',
            name='video_url',
            field=models.URLField(blank=True),
        ),
    ]
