# Generated by Django 5.1.4 on 2026-07-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_hero_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Homepage'), ('about', 'About'), ('contact', 'Contact')], max_length=20)),
                ('section_key', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=255)),
                ('content', models.JSONField(default=dict)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'page_sections',
                'ordering': ['page', 'sort_order'],
                'unique_together': {('page', 'section_key')},
            },
        ),
    ]
