# Generated by Django 5.1.4 on 2026-07-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_vendor_ops_and_page_sections'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunitySocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField(blank=True, default='')),
                ('abbr', models.CharField(max_length=10)),
                ('bg_color', models.CharField(default='#000000', max_length=20)),
                ('text_color', models.CharField(default='#ffffff', max_length=20)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'community_social_links',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HomepageReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('author_initials', models.CharField(blank=True, max_length=4)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('review_date', models.CharField(blank=True, max_length=50)),
                ('text', models.TextField()),
                ('source', models.CharField(choices=[('google', 'Google'), ('admin', 'Staff Pick')], default='admin', max_length=20)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'homepage_reviews',
                'ordering': ['sort_order', '-id'],
            },
        ),
    ]
