# Generated by Django 5.1.4 on 2026-07-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_communitysociallink_homepagereview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesection',
            name='page',
            field=models.CharField(choices=[('home', 'Homepage'), ('about', 'About'), ('contact', 'Contact'), ('product', 'Product Page')], max_length=20),
        ),
    ]
