from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("cms", "0005_alter_pagesection_page")]
    operations = [
        migrations.AddField("heroslide", "headline_en", models.CharField(blank=True, max_length=255, null=True)),
        migrations.AddField("heroslide", "headline_ka", models.CharField(blank=True, max_length=255, null=True)),
        migrations.AddField("heroslide", "headline_ru", models.CharField(blank=True, max_length=255, null=True)),
        migrations.AddField("heroslide", "subline_en", models.TextField(blank=True, null=True)),
        migrations.AddField("heroslide", "subline_ka", models.TextField(blank=True, null=True)),
        migrations.AddField("heroslide", "subline_ru", models.TextField(blank=True, null=True)),
        migrations.AddField("heroslide", "cta_en", models.CharField(blank=True, max_length=100, null=True)),
        migrations.AddField("heroslide", "cta_ka", models.CharField(blank=True, max_length=100, null=True)),
        migrations.AddField("heroslide", "cta_ru", models.CharField(blank=True, max_length=100, null=True)),
        migrations.AddField("banner", "title_en", models.CharField(blank=True, max_length=255, null=True)),
        migrations.AddField("banner", "title_ka", models.CharField(blank=True, max_length=255, null=True)),
        migrations.AddField("banner", "title_ru", models.CharField(blank=True, max_length=255, null=True)),
        migrations.AddField("banner", "subtitle_en", models.TextField(blank=True, null=True)),
        migrations.AddField("banner", "subtitle_ka", models.TextField(blank=True, null=True)),
        migrations.AddField("banner", "subtitle_ru", models.TextField(blank=True, null=True)),
        migrations.AddField("banner", "cta_en", models.CharField(blank=True, max_length=100, null=True)),
        migrations.AddField("banner", "cta_ka", models.CharField(blank=True, max_length=100, null=True)),
        migrations.AddField("banner", "cta_ru", models.CharField(blank=True, max_length=100, null=True)),
        migrations.AddField("faq", "question_en", models.CharField(blank=True, max_length=500, null=True)),
        migrations.AddField("faq", "question_ka", models.CharField(blank=True, max_length=500, null=True)),
        migrations.AddField("faq", "question_ru", models.CharField(blank=True, max_length=500, null=True)),
        migrations.AddField("faq", "answer_en", models.TextField(blank=True, null=True)),
        migrations.AddField("faq", "answer_ka", models.TextField(blank=True, null=True)),
        migrations.AddField("faq", "answer_ru", models.TextField(blank=True, null=True)),
        migrations.AddField("faq", "category_en", models.CharField(blank=True, max_length=50, null=True)),
        migrations.AddField("faq", "category_ka", models.CharField(blank=True, max_length=50, null=True)),
        migrations.AddField("faq", "category_ru", models.CharField(blank=True, max_length=50, null=True)),
        migrations.AddField("announcementbar", "messages_en", models.JSONField(blank=True, null=True)),
        migrations.AddField("announcementbar", "messages_ka", models.JSONField(blank=True, null=True)),
        migrations.AddField("announcementbar", "messages_ru", models.JSONField(blank=True, null=True)),
        migrations.AddField("homepagereview", "text_en", models.TextField(blank=True, null=True)),
        migrations.AddField("homepagereview", "text_ka", models.TextField(blank=True, null=True)),
        migrations.AddField("homepagereview", "text_ru", models.TextField(blank=True, null=True)),
        migrations.AddField("pagesection", "title_en", models.CharField(blank=True, max_length=255, null=True)),
        migrations.AddField("pagesection", "title_ka", models.CharField(blank=True, max_length=255, null=True)),
        migrations.AddField("pagesection", "title_ru", models.CharField(blank=True, max_length=255, null=True)),
        migrations.AddField("pagesection", "content_en", models.JSONField(blank=True, null=True)),
        migrations.AddField("pagesection", "content_ka", models.JSONField(blank=True, null=True)),
        migrations.AddField("pagesection", "content_ru", models.JSONField(blank=True, null=True)),
    ]
