# Generated by Django 5.1.4 on 2026-07-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_multilingual_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementbar',
            name='messages_en',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='announcementbar',
            name='messages_ka',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='announcementbar',
            name='messages_ru',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title_ka',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_ka',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_ru',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_ka',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='headline_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='headline_ka',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='headline_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='homepagereview',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='homepagereview',
            name='text_ka',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='homepagereview',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='content_en',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='content_ka',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='content_ru',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='title_ka',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
