# Generated by Django 5.1.4 on 2026-07-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_translate_page_section_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='trustbaritem',
            name='description_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trustbaritem',
            name='description_ka',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trustbaritem',
            name='description_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trustbaritem',
            name='title_en',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='trustbaritem',
            name='title_ka',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='trustbaritem',
            name='title_ru',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
