# Generated by Django 5.1.4 on 2026-08-08 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_translate_faq_defaults'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcementbar',
            name='messages_ru',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='cta_ru',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='subtitle_ru',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='answer_ru',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='category_ru',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='question_ru',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='cta_ru',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='headline_ru',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='subline_ru',
        ),
        migrations.RemoveField(
            model_name='homepagereview',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='pagesection',
            name='content_ru',
        ),
        migrations.RemoveField(
            model_name='pagesection',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='trustbaritem',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='trustbaritem',
            name='title_ru',
        ),
    ]
