# Generated by Django 5.1.4 on 2026-06-26 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_add_vendor_fk'),
        ('vendors', '0002_vendor_custom_cover_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customorder',
            name='product_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customorder',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_orders', to='vendors.vendor'),
        ),
    ]
