# Generated by Django 5.1.4 on 2026-07-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_delivery_options_cart_gift_wrap_order_extras'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=100)),
                ('est_days_min', models.PositiveSmallIntegerField(default=1)),
                ('est_days_max', models.PositiveSmallIntegerField(default=5)),
                ('price_usd', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('price_gel', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'processing_options',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='cartitem',
            name='processing_option',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='processing_option',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
