# Generated by Django 5.1.4 on 2026-07-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_cartitem_size_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='gift_wrap_image_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='gift_wrap_note',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='gift_wrap_image_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='gift_wrap_note',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
