# Generated by Django 5.1.4 on 2026-07-11 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_vendor_shipping_market_ge_other'),
        ('vendors', '0006_vendor_ops_and_page_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingoption',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processing_options', to='vendors.vendor'),
        ),
        migrations.AlterField(
            model_name='processingoption',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterUniqueTogether(
            name='processingoption',
            unique_together={('vendor', 'slug')},
        ),
    ]
