# Generated by Django 5.1.4 on 2026-07-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_processingoption_is_included'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='processing_days',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='processing_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='processing_label',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='processing_fee_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='processing_days',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='processing_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='processing_label',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
