# Generated by Django 5.1.4 on 2026-07-31 10:04

from django.db import migrations, models


def backfill_english_labels(apps, schema_editor):
    ProcessingOption = apps.get_model("orders", "ProcessingOption")
    for option in ProcessingOption.objects.all().iterator():
        ProcessingOption.objects.filter(pk=option.pk).update(label_en=option.label)


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_order_review_timing'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingoption',
            name='label_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='processingoption',
            name='label_ka',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='processingoption',
            name='label_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.RunPython(backfill_english_labels, migrations.RunPython.noop),
    ]
