# Generated by Django 5.1.4 on 2026-08-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_vendorshippingoption_is_express'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processingoption',
            name='label_ru',
        ),
        migrations.AlterField(
            model_name='ordershipment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vendorshippingoption',
            name='is_express',
            field=models.BooleanField(default=False, help_text='Express/fast shipping. Only shown if all vendor items in the cart are ready to ship.'),
        ),
    ]
