# Generated by Django 5.1.4 on 2026-08-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_remove_processingoption_label_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkout_idempotency_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='checkout_request_fingerprint',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
