"use client"

import React, { useEffect, useState } from "react"
import { Plus, Save, Trash2 } from "lucide-react"
import { adminFetch } from "@/lib/admin-auth"

type Trust = { id: number; key: string; title: string; description: string; icon: string; logos: Array<{ name: string; label: string; bg: string; text: string }>; sort_order: number; is_active: boolean }
type Brand = { id: number; name: string; abbreviation: string; background: string; text_color: string; link: string; sort_order: number; is_active: boolean }
const input = "w-full px-3 py-2 bg-dp-bg-elevated border border-dp-border rounded-sm text-[12px] text-dp-text-primary"

export default function GlobalHomepageSettings() {
  const [trust, setTrust] = useState<Trust[]>([])
  const [brands, setBrands] = useState<Brand[]>([])
  const [newBrand, setNewBrand] = useState({ name: "", abbreviation: "", background: "#111111", text_color: "#ffffff", link: "", sort_order: 0, is_active: true })
  const load = () => Promise.all([adminFetch<Trust[]>("/trust-bar/"), adminFetch<Brand[]>("/fandoms/")]).then(([t, b]) => { setTrust(t); setBrands(b) }).catch(() => {})
  useEffect(() => { void load() }, [])
  async function saveTrust(item: Trust) { await adminFetch(`/trust-bar/${item.id}/`, { method: "PATCH", body: JSON.stringify(item) }); await load() }
  async function saveBrand(item: Brand) { await adminFetch(`/fandoms/${item.id}/`, { method: "PATCH", body: JSON.stringify(item) }); await load() }
  async function addBrand(e: React.FormEvent) { e.preventDefault(); await adminFetch("/fandoms/", { method: "POST", body: JSON.stringify(newBrand) }); setNewBrand({ name: "", abbreviation: "", background: "#111111", text_color: "#ffffff", link: "", sort_order: 0, is_active: true }); await load() }
  async function removeBrand(id: number) { await adminFetch(`/fandoms/${id}/`, { method: "DELETE" }); await load() }
  return <div className="mt-8 grid xl:grid-cols-2 gap-6">
    <section className="border border-dp-border rounded-sm p-5 flex flex-col gap-4"><div><h2 className="font-display text-xl text-dp-text-primary">Global Trust Bar</h2><p className="text-[12px] text-dp-text-tertiary mt-1">Edit delivery, payment, return, and logo information shown site-wide.</p></div>
      {trust.map((item) => <div key={item.id} className="border border-dp-border rounded-sm p-3 flex flex-col gap-2"><input className={input} value={item.title} onChange={(e) => setTrust((all) => all.map((x) => x.id === item.id ? { ...x, title: e.target.value } : x))} placeholder="Title" /><input className={input} value={item.description} onChange={(e) => setTrust((all) => all.map((x) => x.id === item.id ? { ...x, description: e.target.value } : x))} placeholder="Description" /><input className={input} value={item.logos.map((x) => x.label).join(", ")} onChange={(e) => setTrust((all) => all.map((x) => x.id === item.id ? { ...x, logos: e.target.value.split(",").map((label) => ({ name: label.trim(), label: label.trim(), bg: "#111111", text: "#ffffff" })).filter((x) => x.label) } : x))} placeholder="Logos, comma separated" /><div className="flex items-center gap-2"><input type="number" className={input} value={item.sort_order} onChange={(e) => setTrust((all) => all.map((x) => x.id === item.id ? { ...x, sort_order: Number(e.target.value) } : x))} /><button type="button" onClick={() => void saveTrust(item)} className="inline-flex items-center gap-1 px-3 py-2 bg-dp-accent-cta text-white text-[11px] font-bold uppercase rounded-sm"><Save size={12} /> Save</button></div></div>)}
    </section>
    <section className="border border-dp-border rounded-sm p-5 flex flex-col gap-4"><div><h2 className="font-display text-xl text-dp-text-primary">Official Fandoms / Companies</h2><p className="text-[12px] text-dp-text-tertiary mt-1">Add, reorder, hide, and edit the brands in the homepage carousel.</p></div>
      {brands.map((item) => <div key={item.id} className="border border-dp-border rounded-sm p-3 grid grid-cols-2 gap-2"><input className={input} value={item.name} onChange={(e) => setBrands((all) => all.map((x) => x.id === item.id ? { ...x, name: e.target.value } : x))} placeholder="Company name" /><input className={input} value={item.abbreviation} onChange={(e) => setBrands((all) => all.map((x) => x.id === item.id ? { ...x, abbreviation: e.target.value } : x))} placeholder="Display text" /><input className={input} value={item.background} onChange={(e) => setBrands((all) => all.map((x) => x.id === item.id ? { ...x, background: e.target.value } : x))} placeholder="Background color" /><input className={input} value={item.text_color} onChange={(e) => setBrands((all) => all.map((x) => x.id === item.id ? { ...x, text_color: e.target.value } : x))} placeholder="Text color" /><input className={input} type="number" value={item.sort_order} onChange={(e) => setBrands((all) => all.map((x) => x.id === item.id ? { ...x, sort_order: Number(e.target.value) } : x))} /><div className="flex gap-2"><button type="button" onClick={() => void saveBrand(item)} className="inline-flex items-center gap-1 px-3 py-2 bg-dp-accent-cta text-white text-[11px] font-bold uppercase rounded-sm"><Save size={12} /> Save</button><button type="button" onClick={() => void removeBrand(item.id)} className="px-3 py-2 border border-red-400/40 text-red-400 rounded-sm"><Trash2 size={12} /></button></div></div>)}
      <form onSubmit={(e) => void addBrand(e)} className="border border-dp-accent-cta/30 rounded-sm p-3 grid grid-cols-2 gap-2"><input required className={input} value={newBrand.name} onChange={(e) => setNewBrand({ ...newBrand, name: e.target.value })} placeholder="New company name" /><input required className={input} value={newBrand.abbreviation} onChange={(e) => setNewBrand({ ...newBrand, abbreviation: e.target.value })} placeholder="Display text" /><button className="col-span-2 inline-flex justify-center items-center gap-1 px-3 py-2 bg-dp-accent-cta text-white text-[11px] font-bold uppercase rounded-sm"><Plus size={12} /> Add company</button></form>
    </section>
  </div>
}
