# Generated by Django 5.1.4 on 2026-07-11 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_initial'),
        ('promo', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='prize_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='badge',
            name='prize_promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badge_prizes', to='promo.promocode'),
        ),
        migrations.AddField(
            model_name='userbadge',
            name='seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
