# Generated by Django 5.1.4 on 2026-08-17 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_badge_prizes_and_grants'),
        ('orders', '0027_order_checkout_idempotency_key_and_more'),
        ('promo', '0006_alter_userpromogrant_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsMarketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('point_cost', models.PositiveIntegerField()),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('item_type', models.CharField(choices=[('physical', 'Physical Product'), ('digital', 'Digital Voucher')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'points_market_items',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('earned', 'Earned'), ('spent', 'Spent'), ('refunded', 'Refunded'), ('adjustment', 'Adjustment')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('available', 'Available'), ('spent', 'Spent'), ('cancelled', 'Cancelled')], max_length=20)),
                ('points', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('available_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'point_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='userbadge',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='badge',
            name='prize_promo',
        ),
        migrations.RemoveField(
            model_name='userbadge',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='gamificationprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userbadge',
            name='user',
        ),
        migrations.RemoveField(
            model_name='xplog',
            name='user',
        ),
        migrations.DeleteModel(
            name='XPRule',
        ),
        migrations.AddIndex(
            model_name='pointsmarketitem',
            index=models.Index(fields=['is_active', 'stock_quantity'], name='points_mark_is_acti_5ed68a_idx'),
        ),
        migrations.AddIndex(
            model_name='pointsmarketitem',
            index=models.Index(fields=['item_type', 'is_active'], name='points_mark_item_ty_f26f3b_idx'),
        ),
        migrations.AddField(
            model_name='pointtransaction',
            name='market_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_transactions', to='gamification.pointsmarketitem'),
        ),
        migrations.AddField(
            model_name='pointtransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_transactions', to='orders.order'),
        ),
        migrations.AddField(
            model_name='pointtransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Badge',
        ),
        migrations.DeleteModel(
            name='GamificationProfile',
        ),
        migrations.DeleteModel(
            name='UserBadge',
        ),
        migrations.DeleteModel(
            name='XPLog',
        ),
        migrations.AddIndex(
            model_name='pointtransaction',
            index=models.Index(fields=['user', 'status', 'created_at'], name='point_trans_user_id_21712a_idx'),
        ),
        migrations.AddIndex(
            model_name='pointtransaction',
            index=models.Index(fields=['order', 'transaction_type'], name='point_trans_order_i_4f985a_idx'),
        ),
    ]
