# Generated by Django 5.1.4 on 2026-08-17 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0004_pointsmarketitem_pointtransaction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('earned', 'Earned'), ('spent', 'Spent'), ('refunded', 'Refunded'), ('refund_reversal', 'Refund Reversal'), ('adjustment', 'Adjustment')], max_length=20),
        ),
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField()),
                ('scope', models.CharField(max_length=80)),
                ('request_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idempotency_keys', to='gamification.pointtransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_idempotency_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'points_idempotency_keys',
                'indexes': [models.Index(fields=['user', 'scope', 'key'], name='points_idem_user_id_97220b_idx'), models.Index(fields=['status', 'created_at'], name='points_idem_status_06a4c2_idx')],
                'unique_together': {('user', 'scope', 'key')},
            },
        ),
    ]
