# Generated by Django 5.1.4 on 2026-08-17 12:37

from django.db import migrations, models


def seed_loyalty_tiers(apps, schema_editor):
    LoyaltyTierConfig = apps.get_model("gamification", "LoyaltyTierConfig")
    defaults = (
        ("genin", "Genin", 0, 350),
        ("chunin", "Chunin", 350, 1000),
        ("jonin", "Jonin", 1000, None),
    )
    for tier_key, label, min_points, max_points in defaults:
        LoyaltyTierConfig.objects.get_or_create(
            tier_key=tier_key,
            defaults={
                "label": label,
                "min_lifetime_points": min_points,
                "max_lifetime_points": max_points,
                "discount_percent": 0,
                "scope_type": "all",
                "is_active": True,
            },
        )


def unseed_loyalty_tiers(apps, schema_editor):
    LoyaltyTierConfig = apps.get_model("gamification", "LoyaltyTierConfig")
    LoyaltyTierConfig.objects.filter(tier_key__in=["genin", "chunin", "jonin"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0005_alter_pointtransaction_transaction_type_and_more'),
        ('products', '0026_clear_sculpi_material_and_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyTierConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_key', models.CharField(choices=[('genin', 'Genin'), ('chunin', 'Chunin'), ('jonin', 'Jonin')], max_length=20, unique=True)),
                ('label', models.CharField(max_length=80)),
                ('min_lifetime_points', models.PositiveIntegerField()),
                ('max_lifetime_points', models.PositiveIntegerField(blank=True, null=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('scope_type', models.CharField(choices=[('all', 'All products'), ('products', 'Selected products'), ('categories', 'Selected categories'), ('artists', 'Selected artists')], default='all', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artists', models.ManyToManyField(blank=True, related_name='loyalty_tier_configs', to='products.artist')),
                ('categories', models.ManyToManyField(blank=True, related_name='loyalty_tier_configs', to='products.category')),
                ('products', models.ManyToManyField(blank=True, related_name='loyalty_tier_configs', to='products.product')),
            ],
            options={
                'db_table': 'loyalty_tier_configs',
                'ordering': ['min_lifetime_points'],
            },
        ),
        migrations.RunPython(seed_loyalty_tiers, unseed_loyalty_tiers),
    ]
