# Generated by Django 5.1.4 on 2026-08-17 12:46

from django.db import migrations, models


def reset_artist_scoped_tiers(apps, schema_editor):
    LoyaltyTierConfig = apps.get_model("gamification", "LoyaltyTierConfig")
    LoyaltyTierConfig.objects.filter(scope_type="artists").update(scope_type="all")


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0006_loyaltytierconfig'),
    ]

    operations = [
        migrations.RunPython(reset_artist_scoped_tiers, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='loyaltytierconfig',
            name='scope_type',
            field=models.CharField(choices=[('all', 'All products'), ('products', 'Selected products'), ('categories', 'Selected categories')], default='all', max_length=20),
        ),
    ]
