# Generated by Django 5.1.4 on 2026-08-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0007_alter_loyaltytierconfig_scope_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointsmarketitem',
            name='image_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='pointsmarketitem',
            name='main_image_url',
            field=models.URLField(blank=True),
        ),
    ]
