# Generated by Django 5.1.4 on 2026-08-18 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0008_pointsmarketitem_image_urls_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoyaltyTierConfig',
        ),
    ]
