# Generated by Django 5.1.4 on 2026-08-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0009_delete_loyaltytierconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointsmarketitem',
            name='voucher_discount_type',
            field=models.CharField(choices=[('percent', 'Percentage'), ('fixed', 'Fixed Amount')], default='percent', max_length=10),
        ),
        migrations.AddField(
            model_name='pointsmarketitem',
            name='voucher_discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='pointsmarketitem',
            name='voucher_min_order_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
