# Generated by Django 5.1.4 on 2026-08-19 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0011_pointsmarketredemption'),
        ('vendors', '0009_normalize_default_vendor_identities'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointsmarketitem',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_market_items', to='vendors.vendor'),
        ),
    ]
