# Generated by Django 5.1.4 on 2026-08-19 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0012_pointsmarketitem_vendor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsMarketShippingPaymentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('item_name', models.CharField(max_length=160)),
                ('item_image_url', models.URLField(blank=True)),
                ('point_cost', models.PositiveIntegerField()),
                ('shipping_name', models.CharField(max_length=255)),
                ('shipping_line1', models.CharField(max_length=255)),
                ('shipping_line2', models.CharField(blank=True, max_length=255)),
                ('shipping_city', models.CharField(max_length=100)),
                ('shipping_state', models.CharField(max_length=100)),
                ('shipping_zip', models.CharField(max_length=20)),
                ('shipping_country', models.CharField(max_length=100)),
                ('shipping_email', models.EmailField(max_length=254)),
                ('shipping_phone', models.CharField(blank=True, max_length=30)),
                ('shipping_type', models.CharField(max_length=50)),
                ('shipping_label', models.CharField(max_length=100)),
                ('shipping_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('shipping_currency', models.CharField(default='USD', max_length=10)),
                ('expires_at', models.DateTimeField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('market_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_payment_sessions', to='gamification.pointsmarketitem')),
                ('redemption', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_payment_session', to='gamification.pointsmarketredemption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_market_shipping_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'points_market_shipping_payment_sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status', 'created_at'], name='points_mark_user_id_f99d58_idx'), models.Index(fields=['status', 'expires_at'], name='points_mark_status_c3d513_idx')],
            },
        ),
    ]
