# Generated by Django 5.1.4 on 2026-08-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newslettersubscriber',
            name='xp_awarded',
        ),
        migrations.AddField(
            model_name='newslettersubscriber',
            name='welcome_reward_sent',
            field=models.BooleanField(default=False),
        ),
    ]
