# Generated by Django 5.1.4 on 2026-07-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_description_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10),
        ),
        migrations.AddField(
            model_name='productimage',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='products/videos/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
