# Generated by Django 5.1.4 on 2026-07-11 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_sizevariant_sale_prices'),
        ('vendors', '0006_vendor_ops_and_page_sections'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogFilterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('global', 'Global'), ('category', 'Category'), ('vendor', 'Vendor')], max_length=20)),
                ('category_slug', models.CharField(blank=True, default='', max_length=80)),
                ('visible_filters', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filter_configs', to='vendors.vendor')),
            ],
            options={
                'db_table': 'catalog_filter_configs',
                'constraints': [models.UniqueConstraint(fields=('scope', 'category_slug', 'vendor'), name='unique_catalog_filter_config_scope')],
            },
        ),
    ]
