# Generated by Django 5.1.4 on 2026-07-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_add_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_ready_to_ship',
            field=models.BooleanField(default=False),
        ),
    ]
