# Generated by Django 5.1.4 on 2026-07-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_add_is_ready_to_ship'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizevariant',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='size_variants', to='products.productimage'),
        ),
    ]
