# Generated by Django 5.1.4 on 2026-07-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_multilingual_artist_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='bio_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='posterfinish',
            name='label_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='posterframe',
            name='label_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='postersize',
            name='label_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sizevariant',
            name='label_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name_ka',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='posterfinish',
            name='label_ka',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='posterfinish',
            name='label_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='posterframe',
            name='label_ka',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='posterframe',
            name='label_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='postersize',
            name='label_ka',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='postersize',
            name='label_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sizevariant',
            name='label_ka',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sizevariant',
            name='label_ru',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
