# Generated by Django 5.1.4 on 2026-07-31 10:04

from django.db import migrations, models


def backfill_product_translations_and_skus(apps, schema_editor):
    Product = apps.get_model("products", "Product")
    SizeVariant = apps.get_model("products", "SizeVariant")

    for product in Product.objects.all().iterator():
        Product.objects.filter(pk=product.pk).update(
            material_en=product.material,
            processing_time_label_en=product.processing_time_label,
            tags_en=product.tags,
        )

    used = set(SizeVariant.objects.exclude(sku__isnull=True).values_list("sku", flat=True))
    for variant in SizeVariant.objects.select_related("product").all().iterator():
        product_part = "".join(c if c.isalnum() else "-" for c in variant.product.title.upper()).strip("-")[:30]
        label_part = "".join(c if c.isalnum() else "-" for c in variant.label.upper()).strip("-")[:24]
        base = f"KOL-{product_part or 'PRODUCT'}-{label_part or 'VARIANT'}"
        candidate = base
        suffix = 2
        while candidate in used:
            candidate = f"{base[:75]}-{suffix}"
            suffix += 1
        used.add(candidate)
        SizeVariant.objects.filter(pk=variant.pk).update(sku=candidate)


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_translate_seeded_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='material_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='material_ka',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='material_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='processing_time_label_en',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='processing_time_label_ka',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='processing_time_label_ru',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tags_en',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tags_ka',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tags_ru',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AddField(
            model_name='sizevariant',
            name='sku',
            field=models.CharField(blank=True, db_index=True, max_length=80, null=True, unique=True),
        ),
        migrations.RunPython(backfill_product_translations_and_skus, migrations.RunPython.noop),
    ]
