# Generated by Django 5.1.4 on 2026-07-31 10:26

from django.db import migrations, models


DEFAULT_DETAILS = [
    'Printed on 0.045" thick aluminium composite',
    "UV-resistant, fade-proof inks - no frame needed",
    "Comes with 4 magnetic mounting pins, no tools required",
    "Scratch and moisture resistant surface",
    "Made to order - produced within 3 business days",
]


def backfill_english_product_details(apps, schema_editor):
    Product = apps.get_model("products", "Product")
    ProcessingOption = apps.get_model("orders", "ProcessingOption")
    Product.objects.all().update(
        product_details=DEFAULT_DETAILS,
        product_details_en=DEFAULT_DETAILS,
        product_details_ka=[],
        product_details_ru=[],
    )
    for product in Product.objects.exclude(vendor_id=None).iterator():
        option_ids = ProcessingOption.objects.filter(
            vendor_id=product.vendor_id,
            is_active=True,
        ).values_list("id", flat=True)
        product.processing_options.set(option_ids)


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_processingoption_label_en_processingoption_label_ka_and_more'),
        ('products', '0022_product_material_en_product_material_ka_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='processing_options',
            field=models.ManyToManyField(blank=True, related_name='products', to='orders.processingoption'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_details',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='product_details_en',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_details_ka',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_details_ru',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.RunPython(backfill_english_product_details, migrations.RunPython.noop),
    ]
