# Generated by Django 5.1.4 on 2026-08-08 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_sizevariant_is_ready_to_ship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='bio_ru',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='category',
            name='meta_description_ru',
        ),
        migrations.RemoveField(
            model_name='category',
            name='meta_keywords_ru',
        ),
        migrations.RemoveField(
            model_name='category',
            name='meta_title_ru',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='posterfinish',
            name='label_ru',
        ),
        migrations.RemoveField(
            model_name='posterframe',
            name='label_ru',
        ),
        migrations.RemoveField(
            model_name='postersize',
            name='label_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='material_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_description_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_keywords_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_title_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='processing_time_label_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_details_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='sizevariant',
            name='label_ru',
        ),
    ]
